### user create action 
POST http://localhost:3000/users 
Content-Type: application/json

{
  "name": "Piper Halliwell",
  "email": "piper@test.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "piper@test.com",
  "password": "password"
}